export const INITIATE_CAMPAIGN_SEARCH = 'INITIATE_CAMPAIGN_SEARCH';
export const CAMPAIGN_SEARCH_RESULTS_READY = 'CAMPAIGN_SEARCH_RESULTS_READY';
export const ON_CAMPAIGN_PAGE_CHANGE = 'ON_CAMPAIGN_PAGE_CHANGE';
